name: CI/CD for TitanCore

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17 with Maven cache
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        cache-dependency-path: '**/pom.xml' 
        
    - name: Generate application-docker.properties
      run: |
        mkdir -p bbs-core/src/main/resources
        echo "${{ secrets.DOCKER_PROPERTIES }}" > bbs-core/src/main/resources/application-docker.properties



    - name: Build with Maven
      run: mvn package -B -Pdocker -DskipTests

    - name: Set up QEMU (for multiarch)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true


    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Alibaba Cloud Registry
      uses: docker/login-action@v3
      with:
        registry: crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push multi-arch Docker image to Aliyun
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest
          crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:${{ github.sha }}

          
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 221
        script: |
          echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com
          sudo docker pull crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest
          sudo docker stop titan-core || true
          sudo docker rm titan-core || true
          sudo docker run -d --name titan-core -p 8999:8080 --network 1panel-network crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest
          sudo docker network connect es-net titan-core

