name: CI/CD for TitanCore

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Generate application-docker.yml
      run: |
        mkdir -p bbs-core/src/main/resources
        echo "${{ secrets.DOCKER_YML }}" > bbs-core/src/main/resources/application-docker.yaml

        
    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Alibaba Cloud Registry
      uses: docker/login-action@v3
      with:
        registry: crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Aliyun
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 221
        script: |
          docker pull crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest
          docker stop titan-core || true
          docker rm titan-core || true
          docker run -d --name titan-core -p 83:8080 crpi-3vi0uv2gxk2az3c0.cn-guangzhou.personal.cr.aliyuncs.com/patriclee/titan-core:latest
          docker network connect es-net titan-core
